#!/bin/bash
# Make sure to change permissions of this file to make it executable with
# chmod 777 ./stop_services.sh

sudo systemctl stop influxdb
sudo systemctl stop grafana-server
sudo systemctl stop sdr_weather_reading
